### ISSUE TITLE
Broken links on the live website

### ISSUE THREAD

**Issue by Schyzophrenic** [ninsuo/symfony-collection-demo#4]
Hey!
First of all thanks for the scripts and work! 
I checked on the website and the links redirecting to gitHub are mostly broken (404). It is not a big deal as we can find it here, but you should know!

Thanks!

**Comment by ninsuo** [comment]
Thank you, when I added support for Symfony 2.x and 3.x, I forgot to adapt the GitHub helper.
Will fix that in a couple of minutes.
A

**Comment by ninsuo** [comment]
This is fixed for both 2.x and 3.x branches.
A
