### ISSUE TITLE
Demo website menu

### ISSUE THREAD

**Issue by bertyterty** [ninsuo/symfony-collection-demo#9]
When viewing on a mobile browser, the demo website is responsive, however the GitHub link covers the burger menu button so is unusable unless you know the URL you wish to visit. 

Not come across this until now when I thought I would do some reading up of the bundle whilst away from my computer

**Comment by ninsuo** [comment]
Thank you, will fix that asap.
Have a good day!

**Comment by ninsuo** [comment]
Fixed in https://github.com/ninsuo/symfony-collection-demo/commit/95c610d487b4f7f783187aecdd09fe4e636155d0

Have a good day!
Alain
